# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: NDP
version: '0.0.0'
github: "fortlogic/NDP"
license: MIT
author: "Matias Eyzaguirre"
maintainer: "Matias Eyzaguirre"
synopsis: "Nameless Data Processor: an FPGA sized computer"
description: The NDP is an experiment in computer design by an idiot (read amateur)
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.org
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
    - base
    - bytestring
    - clash-prelude
    - constraints
    - data-default
    - filepath
    - ghc-typelits-extra
    - ghc-typelits-knownnat
    - ghc-typelits-natnormalise
    - singletons
  source-dirs: hardware
  # generated-exposed-modules: Paths_NDP
  generated-other-modules: Paths_NDP

data-files:
  - hardware/NDP/Primitive/vhdl/clockStrobe.json

executables:
  ndp:
    source-dirs: executable
    main: Make/Main.hs
    dependencies:
      - NDP
      - base
      - bytestring
      - clash-ghc
      - conf
      - directory
      - netpbm
      - posix-escape
      - safe-globals
      - shake
      - unordered-containers
      - vector
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

benchmarks:
  NDP-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
      - NDP
      - base
      - criterion
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

tests:
  NDP-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
      - NDP
      - QuickCheck
      - base
      - clash-prelude
      - formatting
      - ghc-typelits-extra
      - ghc-typelits-knownnat
      - ghc-typelits-natnormalise
      - hspec
      - tasty
      - tasty-hspec
      - template-haskell
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
